### ISSUE TITLE
PlatformException(Characteristic unavailable, null, null, null)

### ISSUE THREAD

**Issue by mealinux** [woodemi/quick_blue#100]
i got this characteristics
![2022-05-03_22-21](https://user-images.githubusercontent.com/10341948/166540928-c9364f0f-04be-47ad-ab34-410eb9c6c585.png)

then connected and i try read value like this

```
await QuickBlue.readValue(
        '98:F6:21:D4:DE:F1', // this is the phone's mac address
        '00001801-0000-1000-8000-00805f9b34fb',
        '00002a05-0000-1000-8000-00805f9b34fb',
      );
```

but i got this error
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(Characteristic unavailable, null, null, null)
E/flutter ( 8295): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:607
E/flutter ( 8295): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:177
```

**Comment by Sunbreak** [comment]
https://github.com/woodemi/quick_blue/blob/master/quick_blue/README.md#transfer-data-between-ble-central--peripheral

```dart
QuickBlue.readValue(deviceId, serviceId, characteristicId);
```

`deviceId` is peripheral's identifier, got from `ScanResult`, not the central's identifier(i.e. your Android phone's mac address)
