### ISSUE TITLE
Support advanced methods for linux

### ISSUE THREAD

**Issue by CodeDoctorDE** [woodemi/quick_blue#108]
Related to #29 
Currently the linux implementation only supports `isBluetoothAvailable` and `startScan/stopScan`.
It would be useful if linux supports all other methods that windows, android and ios supports.

**Comment by Sunbreak** [comment]
I could add some implementation but am unable to test. Could you test on Linux?

**Comment by CodeDoctorDE** [comment]
Yeah sure.
There are multiple options how to test it:
* Windows Subsystem for Linux (https://docs.microsoft.com/en-us/windows/wsl/install)
* A live cd/usb where you don't need to install (https://ubuntu.com/tutorials/try-ubuntu-before-you-install#1-getting-started)
* A vm (like virtualbox https://www.virtualbox.org/)

**Comment by Sunbreak** [comment]
Yep, I see. I've a lot of devices but locked down inside my home without those testable devices

Maybe this weekend

**Comment by MGlolenstine** [comment]
There is #99 waiting for further elaboration.
It does implement write and read.

**Comment by Sunbreak** [comment]
Fixed by https://github.com/woodemi/quick.flutter/pull/30
