### ISSUE TITLE
Microsoft.Windows.CppWinRT.props was not found in Windows 10

### ISSUE THREAD

**Issue by dirablue** [woodemi/quick_blue#119]
Hi I testeed this plugin but error occurred on Windows 10.

Do you have any idea to fix this?

quick_blue: ^0.5.0-dev.2
windows 10
Visual Studio Community 2022 ( I also installed 2019 )

this error message was displayed when I started bulding flutter project.

```
Launching lib\main.dart on Windows in debug mode...
Building Windows application...
<path of project>\build\windows\plugins\quick_blue_windows\quick_blue_windows_plugin.vcxproj(258,3): error MSB4019: The imported project "<path of project>\build\windows\packages\Microsoft.Windows.CppWinRT\build\native\Microsoft.Windows.CppWinRT.props" was not found. Confirm that the expression in the Import declaration "<path of project>\build\windows\packages\Microsoft.Windows.CppWinRT\build\native\Microsoft.Windows.CppWinRT.props" is correct, and that the file exists on disk.
Exception: Build process failed.
```

It seems the code tried to find "build/windows/packages" folder, but there is no packages folder in my project.

![image](https://user-images.githubusercontent.com/708452/174504517-95ea9b74-4c31-488b-9fff-e3acfc2f5713.png)

**Comment by Sunbreak** [comment]
https://github.com/woodemi/quick_notify/discussions/8

**Comment by dirablue** [comment]
@Sunbreak 

Hi I tried it but the error occurred.
do you have any idea of this?

```
Launching lib\main.dart on Windows in debug mode...
CMake Error at CMakeLists.txt:119 (target_link_libraries):
  Cannot specify link libraries for target "PRIVATE" which is not built by
  this project.
 ```

line: 119
```
target_link_libraries(${PLUGIN_NAME} PRIVATE
  ${CMAKE_BINARY_DIR}/packages/Microsoft.Windows.CppWinRT/build/native/Microsoft.Windows.CppWinRT.targets
)
################ NuGet import end ################
```

**Comment by Sunbreak** [comment]
Could you try `local_auth`?

The `CMakeLists.txt` is inspired by https://github.com/flutter/flutter/issues/32719#issuecomment-1136341840

**Comment by dirablue** [comment]
@Sunbreak 

Thank you for sharing this.

I could install CppWinRT with steps following.

1. set Package Sources of nuget in Visual Studio 2022


![kIpZzbiAcF](https://user-images.githubusercontent.com/708452/174741647-a7252d30-aae1-4543-88b9-d531b1095948.png)


2. Add these to last line of CMakeLists.txt in <workspace>/windows folder

```
set(CPPWINRT_VERSION "2.0.220608.4")

find_program(NUGET nuget)
if (NOT NUGET)
    message("Nuget.exe not found, trying to download or use cached version.")
endif()

execute_process(COMMAND
    ${NUGET} install Microsoft.Windows.CppWinRT -Version ${CPPWINRT_VERSION} -OutputDirectory packages
    WORKING_DIRECTORY ${CMAKE_BINARY_DIR}
    RESULT_VARIABLE ret)
if (NOT ret EQUAL 0)
    message(FATAL_ERROR "Failed to install nuget package Microsoft.Windows.CppWinRT.${CPPWINRT_VERSION}")
endif()

```

but after the app starts, another error occurred and crashed if I used this plugin in flutter.
when I don't use this plugin, the app starts correctlly.

```
[   +7 ms] Error connecting to the service protocol: failed to connect to
           http://127.0.0.1:63658/W0h2o9fuOSI=/
```

should I prepare something ..?

**Comment by dirablue** [comment]
https://github.com/woodemi/quick_blue/issues/80#issuecomment-1086327365

it seems there is a same thing.
let me check this..

**Comment by dirablue** [comment]
It works after I switched from Visual Studio 2022 to 2019.
Thanks !
