### ISSUE TITLE
MacOS no devices are found

### ISSUE THREAD

**Issue by ot-repo** [woodemi/quick_blue#121]
Hello,

I am trying quick_blue on Mac. However, no device is found. No error occurs, only the result stream is always empty.

I appreciate any help, thank you!

`QuickBlue.scanResultStream.listen((event) {
    foundDevices.add(event); // never called 
});
QuickBlue.startScan();`

**Comment by Sunbreak** [comment]
Have you tried the example? You have to declare permission in your APP's `info.plist`

https://developer.apple.com/documentation/bundleresources/information_property_list/nsbluetoothalwaysusagedescription

**Comment by ot-repo** [comment]
Unfortunately the example is not working, either.

**Comment by Sunbreak** [comment]
Could you add:

- `flutter doctor -v`
-  Screen recording or screen shot
- Other possible logs

**Comment by ot-repo** [comment]
Here is the `flutter doctor -v` Screen recording will follow.

```
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.2.1 21D62 darwin-arm (Rosetta), locale en-GB)
    • Flutter version 3.0.2 at /Users/sinanc/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (4 weeks ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/sinanc/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5284.31

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.44.0

[✓] Connected device (3 available)
    • iPad Air (5th generation) (mobile) • FD383DE2-07DF-4185-9B5F-48DD483F4993 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)                    • macos                                • darwin-arm64   • macOS 12.2.1 21D62 darwin-arm
      (Rosetta)
    • Chrome (web)                       • chrome                               • web-javascript • Google Chrome 103.0.5060.53

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```

**Comment by ot-repo** [comment]
Here is the video screen:

https://user-images.githubusercontent.com/71355727/177490498-d29999d0-b333-4da7-94c1-53f6b1fa50a6.mp4

**Comment by Sunbreak** [comment]
Could you `open quick_blue_example/macos/Runner.xcworkspace` and `CMD + R` to debug?

**Comment by ot-repo** [comment]
In debug it did work. It asked me in the beginning that the app wants to use the bluetooth. I don't get this, when I start the app via flutter.

**Comment by Sunbreak** [comment]
> In debug it did work. It asked me in the beginning that the app wants to use the bluetooth. I don't get this, when I start the app via flutter.

Actually you did launch the Flutter APP via `VS Code` and it runned as a subprocess. `VS Code` does not have permission of bluetooth and the Flutter APP failed without any warning

If you launch the APP via command line or XCode, it should work

**Comment by ot-repo** [comment]
Thanks for the info! However, it must be a way to run the app via VS Code, as we need to debug the flutter code. It's the same with IntelliJ.

**Comment by ot-repo** [comment]
The same issue is tracked under flutter_blue, as well.

https://github.com/pauldemarco/flutter_blue/issues/1011

**Comment by Sunbreak** [comment]
Yep. Flutter issue is here: https://github.com/flutter/flutter/issues/96369
