### ISSUE TITLE
Multiple devices connected on the same printer

### ISSUE THREAD

**Issue by ot-repo** [woodemi/quick_blue#122]
Hello,

is it possible that multiple devices(iOS, Android, MacOS) connect the same printer at the same time?

It seems that if a device is already connected to the printer, other devices cannot discover the printer anymore. 

Should I always close the connection after printing is finished or should I leave it opened for a better performance?

Thank you and Best Regards!

**Comment by Sunbreak** [comment]
Flutter APPs is central and the printer is a peripheral. You need to contact the printer's manufacturer to confirm `whether the peripheral is available for other central devices after connected`

For example Apple Airpod could be connected to two central

https://support.apple.com/en-us/HT212204
