### ISSUE TITLE
Exception: Unable to generate build files

### ISSUE THREAD

**Issue by husamhamu** [woodemi/quick_blue#17]
I am getting this error when I run the app 
`NUGET.EXE not found.
CMake Error at flutter/ephemeral/.plugin_symlinks/quick_blue_windows/windows/CMakeLists.txt:10 (message):
  Please install this executable, and run CMake again.`

**Comment by Sunbreak** [comment]
Install `NuGet` into your `%PATH%`

- via `Chocolate`: https://chocolatey.org/, `choco install nuget.commandline`
- via `winget`: https://github.com/microsoft/winget-cli, `winget install XXX`
- via website: `https://www.nuget.org/`
