### ISSUE TITLE
Support for Linux?

### ISSUE THREAD

**Issue by flukejones** [woodemi/quick_blue#29]
Canonical has implemented a Linux Bluetooth support [package](https://github.com/canonical/bluez.dart) using bluez.

**Comment by Sunbreak** [comment]
`QuickBlue` is mainly maintained for `NotepadCore` for ourselves.
We would consider supporting Web before Linux, as there is Web support in `NotepadCore`: https://github.com/woodemi/notepad_core/blob/cbf649b44576b808a5fd5d9ce0a2e592492e84a6/notepad_core_web/lib/notepad_core_web.dart#L34

Not quite familiar with Linux & `bluez`. Any contributions are welcome

I'll leave the issue open for further reference

**Comment by Sunbreak** [comment]
FYI @rohitsangwan01 is working on https://github.com/woodemi/quick_blue/pull/63

**Comment by Sunbreak** [comment]
fix by #61

**Comment by CodeDoctorDE** [comment]
Hello, it would be cool if `setValue` can be supported by Linux.
I want to communicate cross platform between my apps. Thanks!

**Comment by Sunbreak** [comment]
Maybe another issue?
