### ISSUE TITLE
Name of the device isn't correct[Windows]

### ISSUE THREAD

**Issue by husamhamu** [woodemi/quick_blue#34]
For example instead of getting the name: HC-05 I got values like: 98 etc.

**Comment by Sunbreak** [comment]
All platforms or only Windows?

**Comment by husamhamu** [comment]
I guess only windows, because I didn't try other platforms

**Comment by Sunbreak** [comment]
Could you try on Android/iOS if you have a mobile development environment?

Or try LightBlue: https://punchthrough.com/lightblue/ -- [iOS](https://apps.apple.com/us/app/lightblue/id557428110), [Android](https://play.google.com/store/apps/details?id=com.punchthrough.lightblueexplorer&hl=en_US)

**Comment by husamhamu** [comment]
Ok , I tried LightBlue on Android. It is also not working for me. It can't find the device that I am trying to connect to

**Comment by Sunbreak** [comment]
It is probably that the device set the name characteristic using wrong encoding.
You'd better debug the device with LigthBlue first.

**Comment by husamhamu** [comment]
Actually I am using flutter_bluetooth_serial plugin on Android and it worked fine. That's why I think the problem is from quick_blue plugin.

**Comment by Sunbreak** [comment]
[flutter_bluetooth_serial](https://pub.dev/packages/flutter_bluetooth_serial): Flutter basic implementation for Classical Bluetooth (only `RFCOMM` for now).
[quick_blue](https://pub.dev/packages/quick_blue): A cross-platform (Android/iOS/macOS/Windows) `BluetoothLE` plugin for Flutter 

RfComm is quite different from BLE: https://stackoverflow.com/questions/50503701/reading-data-from-a-bluetooth-device-low-energy-rfcomm-python3

**Comment by husamhamu** [comment]
Sorry!,  I didn't know this.

**Comment by Sunbreak** [comment]
https://github.com/microsoft/Windows-universal-samples/tree/master/Samples/BluetoothRfcommChat

**Comment by Sunbreak** [comment]
There is an example for Windows API: https://github.com/microsoft/Windows-universal-samples/tree/master/Samples/BluetoothRfcommChat

Contributions are welcome.
