### ISSUE TITLE
help with plugin documenation

### ISSUE THREAD

**Issue by Balrog16** [woodemi/quick_blue#38]
Can you please tell me where did you find the documentation for windows plugins?
This is not an issue only a request for help

**Comment by Sunbreak** [comment]
There are few docs about windows plugins. I copy most from https://github.com/flutter/plugins

**Comment by Balrog16** [comment]
Thank you so much. Yes I've seen these ones, I was wondering that there is no documentation as such except that I see 
https://engine.chinmaygarde.com/classflutter_1_1_stream_handler.html#af6ae35b31d91c5fc8cb926d8e0d916c8
