### ISSUE TITLE
Unable to use on Windows

### ISSUE THREAD

**Issue by Danau5tin** [woodemi/quick_blue#41]
```
NUGET.EXE not found.
CMake Error at flutter/ephemeral/.plugin_symlinks/quick_blue_windows/windows/CMakeLists.txt:10 (message):
  Please install this executable, and run CMake again.


Exception: Unable to generate build files

```

**Comment by Sunbreak** [comment]
You should install https://www.nuget.org/ in you %PATH%

OR manully run `Install-Package Microsoft.Windows.CppWinRT` in [Visual Studio Package Manage Console](Package Manager Console) after you open the generated `runner.sln` in example's build directory

**Comment by Sunbreak** [comment]
Check https://github.com/woodemi/quick_notify/issues/5#issuecomment-888743117 and https://github.com/woodemi/quick_notify/discussions/8
