### ISSUE TITLE
JBL Go bluetooth speaker not show in scan result

### ISSUE THREAD

**Issue by sauravedison** [woodemi/quick_blue#42]

**Comment by Sunbreak** [comment]
Could your scan with LigthBlue and post the information of `JBL Go` device?

LightBlue manual: https://punchthrough.com/lightblue/

- Android: https://play.google.com/store/apps/details?id=com.punchthrough.lightblueexplorer
- iOS/macOS for US: https://play.google.com/store/apps/details?id=com.punchthrough.lightblueexplorer

**Comment by sauravedison** [comment]
Hi,

Just check with LigthBlue Android app it is only display IOS device not display android and JBL GO Speaker.
 
JBL Go : https://www.amazon.in/JBL-Portable-Wireless-Bluetooth-Speaker/dp/B00TFGWAA8

**Comment by Sunbreak** [comment]
I'm sorry if `quick_blue` is the same as LightBlue.

Some HID device is not discoverable via iOS's BLE APIs. The system handle those HID scan results itself

There was a hack way to get the result. I'm not sure whether it works still

**Comment by Sunbreak** [comment]
https://colemancda.github.io/2018/03/25/Hacking-IOBluetooth

**Comment by sauravedison** [comment]
I have run quick_blue in android device which works find but when i scan i got near by IOS device only (not get android device and other bluetooth device)

Why it is not finding near by android device as well ?

In Android Native Code working perfectly all this things.(which i have create demo)

**Comment by Sunbreak** [comment]
Sorry I'm too busy these days to resolve the issue. PRs are welcome

**Comment by Sunbreak** [comment]
I'd like to close it without further info
